### ISSUE TITLE
Use "should" in test description as default?

### ISSUE THREAD

**Issue by soanvig** [andys8/vscode-jest-snippets#10]
It would be very nice to be able to setup texts displayed in `test()`. 

Personally I don't use `should *do things*`, so I need to delete 'should' word every time I use the snippet.

**Comment by andys8** [comment]
Hm, I see your point. Sadly snippets aren't configurable. But I'm thinking about removing the "should". There are `it` and `test`. Perhaps removing it from one is a compromise but it's also inconsistent.

**Comment by soanvig** [comment]
After asking few people I found out, that it is very common convention to use *should*. Maybe it's not that bad idea to stick with it?

**Comment by andys8** [comment]
I'll keep this issue open for now. Perhaps there will be others adding their opinions.

**Comment by franciscolourenco** [comment]
http://www.betterspecs.org/#should
https://github.com/should-not/should_not

If you decide to keep the should, I would suggest at least selecting it by default and removing the rest. That way it would be relatively easy both for should and for should_not to write their description. Like this:

<img width="159" alt="screen shot 2018-06-14 at 15 19 16" src="https://user-images.githubusercontent.com/208149/41414499-80fd53d4-6fe6-11e8-963f-f0eaadfe5a0a.png">

**Comment by andys8** [comment]
Probably the best UX for both.

**Comment by andys8** [comment]
Changed the behavior: https://github.com/andys8/vscode-jest-snippets/commit/e6bd3b24bc636bfa1435a97e9872753b77c399b4

**Comment by franciscolourenco** [comment]
It would still be nice to have an option to disable it.. you know, to prevent bad habits 😄

**Comment by andys8** [comment]
As far as I know, there are currently no options or configurations available for snippets in vscode? Do you have a specific solution in mind?
