### ISSUE TITLE
Use double quotes instead of single

### ISSUE THREAD

**Issue by DamianRivas** [andys8/vscode-jest-snippets#13]
Can you make the snippet use double quotes instead of single quotes? It's annoying when I have a word like `it's` in the test description.

**Comment by andys8** [comment]
Too many people rely on single quotes. And there is no configuration  support for snippets: https://code.visualstudio.com/docs/editor/userdefinedsnippets

See #2. You can modify the snippets and use them as custom snippets or use format on save and escape text like `it's`.

**Comment by DamianRivas** [comment]
That's a bummer! I'll write my own. Anyway, thanks for the handy extension :)
