### ISSUE TITLE
Cut: unexpected "this" operator

### ISSUE THREAD

**Issue by GoGoris** [andys8/vscode-jest-snippets#16]
Hi, 

I think that I found a bug in the 'cut' snippet. It generates "this.cut = ..." but this does not compile because cut is a method variable and not a class variable.

**Expected**

describe('Name of the group', () => {
    let cut;
  
    beforeEach(() => {
      cut = 'test';
    });
  
    test('should behave...', () => {
      expect(this.cut).toBe('test');
    });
  });

**Actual**

describe('Name of the group', () => {
    let cut;
  
    beforeEach(() => {
      this.cut = 'test';
    });
  
    test('should behave...', () => {
      expect(this.cut).toBe('test');
    });
  });
^does not work for me... ("cut is never assigned")

**Comment by andys8** [comment]
You're right. Thanks.
