### ISSUE TITLE
testa

### ISSUE THREAD

**Issue by pavelloz** [andys8/vscode-jest-snippets#32]
Currently snippet looks like this:

```
test('should ', async () => {
    
});
```

It is common to use `done()` when working with callback based async code.

I propose change:
```
test('should ', async done => {

  done();
});
```

**Comment by andys8** [comment]
Jest documentation isn't doing this.

https://jestjs.io/docs/en/asynchronous.html#async-await

`done` is used for callbacks, but not for `async/await`.

**Comment by pavelloz** [comment]
Yep, and a lot of people use callbacks, ie when testing using stdlib nodejs methods ;)

**Comment by andys8** [comment]
Can you provide some evidence where people recommend doing this and explaining the background?

**Comment by pavelloz** [comment]
https://jestjs.io/docs/en/asynchronous#callbacks

**Comment by andys8** [comment]
They never use the *combination* of `async` and `done` on this page. `done` is used for callbacks and `async` for `async/await`.

**Comment by pavelloz** [comment]
Ouh i see what you mean now.
I assumed everyone is using `async` anyways because usually in test cases you depend on something `promise`d anyways, but in case of callbacks you also need `done()`.

Maybe i have just weird tests.

**Comment by andys8** [comment]
I think `async/await` is meant to be a replacement for callbacks (and therefore `done`). Feel free to create a local snippet in VSCode for your use case. I wouldn't add it to the extension.
