### ISSUE TITLE
add support for mocking functions

### ISSUE THREAD

**Issue by danielo515** [andys8/vscode-jest-snippets#35]
Hello, thanks for this extension. It really saves me time when writing expects and that stuff.
However, I have to open the jest documentation too often to check the actual names of the mocking function methods. `mockImplementationOnce`,`mockRejectedValueOnce`, `mockRejectedValue` and others are a nightmare to type and to remember.
Will you consider adding them?

**Comment by andys8** [comment]
Hey.

These are methods defined on jests mock function object. Therefore I would think it's possible that the an editor can autocomplete them without the need of snippets.

They're typed here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3fd9f73e8391611b7309edbd430b083e0102da89/types/jest/index.d.ts#L1296

Is vscode offereing these autocompletions (JavaScript/TypeScript)?

**Comment by danielo515** [comment]
Wow, I was not expecting that fast answer, impressive.
Well, at least for me VSCode is not offering any autocompletion related to jest.
I was thinking about using placeholders, so you have the oportunity to put the actual target object. Something like `$1.mockRejectedValueOnce($2)`.

Another great candidate (because it is a pain to type) is `expect($1).rejects.toThrow($2)`.

Does VSCode offer that completions to you?

**Comment by andys8** [comment]
I generally think these kind of autocompletions should be solved by ide's and language servers. Snippets might be the wrong tool, but you can add them to [your local snippets file](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets).

Completions seem to work pretty good for me. But this is a typescript project. I don't know in terms of plain js. Could work, but could also be the case that some work needs to be done to get better autocompletions.

![image](https://user-images.githubusercontent.com/13085980/68476966-7ac88680-022c-11ea-9dd2-cc7d5382de40.png)

![image](https://user-images.githubusercontent.com/13085980/68476996-8caa2980-022c-11ea-87af-e6e6a4948a60.png)

![image](https://user-images.githubusercontent.com/13085980/68477017-99c71880-022c-11ea-89b8-8ac22b5db7a7.png)

And a js file:

![image](https://user-images.githubusercontent.com/13085980/68477084-c7ac5d00-022c-11ea-93e7-1337e92886e7.png)

**Comment by danielo515** [comment]
well, lucky you 🤣
You can close this issue since it seems that serves no purpose other than fix an IDE problem.

regards

**Comment by andys8** [comment]
Okay 😁
