### ISSUE TITLE
FR: allow toBe to tab out of the last bracket

### ISSUE THREAD

**Issue by gregveres** [andys8/vscode-jest-snippets#39]
Hi

Nice set of snippets! It is very comprehensive and helpful. I have a suggestion that would make them even better in my opinion. 

For some snippets, you add a final cursor position that is after the statement: 
```JS
  "toBeFalsy": {
    "body": "expect($1).toBeFalsy();$0",
    "description": "expects the argument is falsy",
    "prefix": "tbf",
    "scope": "typescript"
  },
```
but for others you do not:
```JS
  "toMatch": {
    "body": "expect($1).toMatch($0);",
    "description": "returns true if the argument matches the second value",
    "prefix": "tm",
    "scope": "typescript"
  },
```

I suggest that all the one-liner snippets should follow the form of the toBeFalsy snippet by having the $0 at the end of the line. This makes it so easy to tab through the contents and be ready to enter the next line. So toMatch would be:
```JS
  "toMatch": {
    "body": "expect($1).toMatch($2);$0",
    "description": "returns true if the argument matches the second value",
    "prefix": "tm",
    "scope": "typescript"
  },
```

**Comment by andys8** [comment]
Hey, thanks for the idea. It would have the advantage to be at the the end of the line and the disadvantage of a forced additional tab. Because of the amount of users that are expecting the current behavior, I'd avoid introducing this change. Feel free to fork and customize the snippets for yourself :)

**Comment by gregveres** [comment]
That's reasonable. I have already made a copy of your excellent snippets because I wanted to make other changes. I will close the issue.
