### ISSUE TITLE
Publish on open-vsx.org

### ISSUE THREAD

**Issue by jaredmoody** [andys8/vscode-jest-snippets#42]
I'd like to use this extension with VSCodium (The FOSS version of VSCode), which for legal reasons has to use its own extension marketplace.

Would you be willing to publish this extension on open-vsx.org?

Thanks!

**Comment by andys8** [comment]
Hi @jaredmoody, thanks for the idea and sorry for the late answer.

I'm torn apart if it's worth supporting/publishing to a second marketplace. From your gut feeling, how many users/downloads would you expect for this extension?

**Comment by jaredmoody** [comment]
Hard to say, but fewer for sure. Perhaps as a sample, the Jest plugin has 550k installs on marketplace.visualstudio.com and 1.7k installs on open-vsx.org. If the same ratios held, a few hundred additional installs for this extension.

I have no idea how difficult it is to publish one additional location, I would hope it would be just a one-time setup. There's a github action to auto-publish here: https://github.com/HaaLeo/publish-vscode-extension#readme

**Comment by andys8** [comment]
Hey, not planned to do this myself, but if you want to feel free to publish the extension there. Would be fine from my side.
