### ISSUE TITLE
Add $0 at the end of each snippet

### ISSUE THREAD

**Issue by IgnacioFigueroa** [andys8/vscode-jest-snippets#48]
So tab key can be used to get out of the snippet

**Comment by andys8** [comment]
`$0` is meant to be placed at locations where it would make sense to end the snippet. This is in most cases not the end of the line. Do you have ideas for specific changes?

**Comment by IgnacioFigueroa** [comment]
Yeah! For example in this snippet
 `"toBeGreaterThan": {
    "body": "expect($1).toBeGreaterThan($0);",
    "description": "expects the argument is greater than or equal",
    "prefix": "tbgt",
    "scope": "source.js"
  },`

The $0 is where a $2 is suposed to be. I think that it should be like 
`expect($1).toBeGreaterThan($2);$0`

**Comment by andys8** [comment]
I can see how this would make sense for `expect`s that take 2 arguments. Changes included in https://github.com/andys8/vscode-jest-snippets/releases/tag/v1.9.1
