### ISSUE TITLE
it + TAB does not autocomplete

### ISSUE THREAD

**Issue by omer-g** [andys8/vscode-jest-snippets#51]
The `it + TAB` shortcut does not work for some reason. Other shortcuts work well.

**Comment by andys8** [comment]
Can't reproduce. Could you demonstrate the issue further and make sure it's an issue with the extension and not the system your working on?



https://user-images.githubusercontent.com/13085980/180613908-f6211f7c-c063-4838-91f4-9f7348d30d10.mp4

**Comment by SantoJambit** [comment]
@andys8 I have the same issue. I have an idea why this might not work:
![image](https://github.com/andys8/vscode-jest-snippets/assets/53570854/baa0d700-2232-4c2c-9265-315654fe8e77)
As you can see, in the dropdown that automatically appears, your snippet appears as second element. I think it needs to be the first element for the tab autocomplete to work.

When I change this setting from inline to top, it works.. not sure yet if I'm going to like that though:
![image](https://github.com/andys8/vscode-jest-snippets/assets/53570854/59a7be42-2677-4359-a520-9e08d491fd6e)

I just saw, that you mention this in your readme, but it's quite hidden at the bottom and looks more like a suggestion

**Update:** Yeah, that setting doesn't work for me.. autocompletion then only works for snippets. Properties are completely gone  then. I guess I'll have to use arrow keys to navigate to the it block then.
