### ISSUE TITLE
Provide configurable option for new lines (\n) before and after snippets

### ISSUE THREAD

**Issue by devert** [andys8/vscode-jest-snippets#6]
Most of the snippets include a new line before and after, by default, when the snippet is expanded. This is a minor annoyance since I am used to typing in the new lines myself and haven't experienced other snippet extensions that do this by default in other editors. I'd like to suggest making this configurable, for users that do not want this to happen by default, as an improvement to the extension.

**Comment by andys8** [comment]
Are you aware of a way to configure snippet extensions in vs code?

**Comment by devert** [comment]
I'm still new to VSCode and don't have any experience writing extensions, so unfortunately I'm not aware of a specific way to do it or if it's possible. If it's not, would you ever consider removing the line breaks from the snippets?

**Comment by andys8** [comment]
I think there is currently no way that allows you to create configurable snippet extensions.

https://code.visualstudio.com/docs/editor/userdefinedsnippets

I think your argument is valid that possibly more people would expect snippets not to create new lines. Therefore I'm open to change this behavior. I'll try to get to changing it in the coming days.

**Comment by andys8** [comment]
Made the changes. Released as 1.1.0.

**Comment by devert** [comment]
Awesome! Thank you!
